PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_games` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`title` text NOT NULL,
	`coverUrl` text,
	`heroUrl` text,
	`igdbId` integer UNIQUE,
	`sgdbId` integer,
	`officialPlatforms` text,
	`releaseYear` integer,
	`hltbMain` real,
	`hltbMainExtras` real,
	`hltbCompletionist` real,
	`notes` text,
	`executablePath` text,
	`developer` text,
	`publisher` text,
	`installDirectory` text,
	`installSizeBytes` integer,
	`genres` text,
	`endless` integer DEFAULT false NOT NULL,
	`isEmulated` integer DEFAULT false NOT NULL,
	`planned` integer DEFAULT false NOT NULL,
	`addedAt` integer NOT NULL,
	`saveBackupEnabled` integer DEFAULT false NOT NULL,
	`saveDetectionSource` text,
	`saveLudusaviName` text,
	`saveCustomPaths` text,
	`curiositiesGeneratedAt` integer,
	`steamAppId` integer,
	`steamAppIdCheckedAt` integer,
	`achievementsSyncedAt` integer,
	`achievementsUnlocksSyncedAt` integer,
	`raGameId` integer,
	`raCheckedAt` integer,
	`ratingCritics` real,
	`ratingCriticsCount` integer,
	`ratingUsers` real,
	`ratingUsersCount` integer,
	`ratingsCheckedAt` integer,
	`summary` text,
	`igdbCollections` text,
	`steamTags` text,
	`steamPositive` integer,
	`steamNegative` integer,
	`steamSpyCheckedAt` integer,
	`planPinnedAt` integer,
	`releaseDate` integer,
	`releaseDatePrecision` text
);
--> statement-breakpoint
INSERT INTO `__new_games`(`id`, `title`, `coverUrl`, `heroUrl`, `igdbId`, `sgdbId`, `officialPlatforms`, `releaseYear`, `hltbMain`, `hltbMainExtras`, `hltbCompletionist`, `notes`, `executablePath`, `developer`, `publisher`, `installDirectory`, `installSizeBytes`, `genres`, `endless`, `isEmulated`, `planned`, `addedAt`, `saveBackupEnabled`, `saveDetectionSource`, `saveLudusaviName`, `saveCustomPaths`, `curiositiesGeneratedAt`, `steamAppId`, `steamAppIdCheckedAt`, `achievementsSyncedAt`, `achievementsUnlocksSyncedAt`, `raGameId`, `raCheckedAt`, `ratingCritics`, `ratingCriticsCount`, `ratingUsers`, `ratingUsersCount`, `ratingsCheckedAt`, `summary`, `igdbCollections`, `steamTags`, `steamPositive`, `steamNegative`, `steamSpyCheckedAt`, `planPinnedAt`, `releaseDate`, `releaseDatePrecision`) SELECT `id`, `title`, `coverUrl`, `heroUrl`, `igdbId`, `sgdbId`, `officialPlatforms`, `releaseYear`, `hltbMain`, `hltbMainExtras`, `hltbCompletionist`, `notes`, `executablePath`, `developer`, `publisher`, `installDirectory`, `installSizeBytes`, `genres`, `endless`, `isEmulated`, `planned`, `addedAt`, `saveBackupEnabled`, `saveDetectionSource`, `saveLudusaviName`, `saveCustomPaths`, `curiositiesGeneratedAt`, `steamAppId`, `steamAppIdCheckedAt`, `achievementsSyncedAt`, `achievementsUnlocksSyncedAt`, `raGameId`, `raCheckedAt`, `ratingCritics`, `ratingCriticsCount`, `ratingUsers`, `ratingUsersCount`, `ratingsCheckedAt`, `summary`, `igdbCollections`, `steamTags`, `steamPositive`, `steamNegative`, `steamSpyCheckedAt`, `planPinnedAt`, `releaseDate`, `releaseDatePrecision` FROM `games`;--> statement-breakpoint
DROP TABLE `games`;--> statement-breakpoint
ALTER TABLE `__new_games` RENAME TO `games`;--> statement-breakpoint
PRAGMA foreign_keys=ON;